[package]
name = "fds-toolbox-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3"

bicubic = "0.1"
makima_spline = "1.1"

fds-toolbox-core = { path = "../../fds-toolbox-core" }