[package]
name = "fds-toolbox-ui-iced"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.5", features = ["canvas", "tokio"] }
# iced_aw = { version = "0.2", default-features = false, features = ["tabs", "tab_bar"] }

plotters = "0.3"
# TODO: Use stable version when it's released
plotters-iced = { version = "0.4", git = "https://github.com/blenderfreaky/plotters-iced", branch = "next" }

# makima_spline = "1.1"
tracing = "0.1"

fds-toolbox-core = { path = "../../fds-toolbox-core" }