[package]
name = "modular-ui-iced"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.4", features = ["canvas", "tokio"] }

plotters="0.3"
plotters-iced = "0.3"

iced_lazy = "0.1"
iced_native = "0.5"