[package]
name = "fds-toolbox-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
druid = "0.7"

modular-ui-dioxus = { path = "../modular-ui-dioxus" }
fds-toolbox-core = { path = "../fds-toolbox-core" }